language: java
jdk:
    - openjdk6
before_install:
    # From http://stackoverflow.com/a/11069162
    - sudo apt-get update
    # To compile 32-bit Linux binaries even though we're on 64 bit.
    - sudo apt-get install libc6-dev-i386 lib32stdc++6 gcc-multilib g++-multilib
    # To compile 32-bit and 64-bit Windows binaries.
    - sudo apt-get install aptitude
    - sudo aptitude install -y mingw-w64
script:
    - ./gradlew jar
    - java -jar build/libs/jtnoodle-0.1-SNAPSHOT.jar
