language: java
jdk:
    - openjdk6
before_install:
    # From http://stackoverflow.com/a/11069162
    - sudo apt-get update
    - sudo apt-get install libc6-dev-i386 lib32stdc++6 gcc-multilib g++-multilib
    # From http://askubuntu.com/a/453136
    #- sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
    #- sudo apt-get update
    #- sudo apt-get install ia32-libs
script:
    - ./gradlew jar
    - java -jar build/libs/jtnoodle-0.1-SNAPSHOT.jar
