/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTNoodle */

#ifndef _Included_JTNoodle
#define _Included_JTNoodle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JTNoodle
 * Method:    getShortPuzzleName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JTNoodle_getShortPuzzleName
  (JNIEnv *, jclass, jint);

/*
 * Class:     JTNoodle
 * Method:    generateScramble
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JTNoodle_generateScramble
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
