/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTNoodle */

#ifndef _Included_JTNoodle
#define _Included_JTNoodle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JTNoodle
 * Method:    summer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JTNoodle_summer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
